### ISSUE TITLE
TypeError: emulator is not a constructor

### ISSUE THREAD

**Issue by Danster21** [navaneethkm004/Discord-Gamebuay#7]
I've npm installed all the proper files, created the proper folders and referenced files (roms and index.json). I can't think of anything on my end I could have done incorrectly. When I try and start any game I get:

```
TypeError: emulator is not a constructor
    at ChannelState.startGame (C:\Users\danny\Downloads\Games\Gamebot\Discord-Gamebuay-main\src\ChannelState.js:122:21)
    at async Bot.<anonymous> (C:\Users\danny\Downloads\Games\Gamebot\Discord-Gamebuay-main\src\index.js:36:20)
```

I went to the referenced locations and saw this in ChannelState.js:

```
			this.config = config;
			let ret;
			
			const emulator = emulators[config.emulator || "default"];
			
			if(data.rom){
				//start up the game
				this.emulator = new emulator(data.rom, "ROM");
				ret = await this.emulator.advance(config.initdelay, speed);
				
				//save the state to eliminate future startup times
				await this.saveState(true);
```

I looked up how to solve the error and it sounds to me like there are a lot of different issues that could throw an Object is not a constructor error. I don't have in depth knowledge of javascript but I think it has something to do with the `new` in the `this.emulator` line. When I remove it and restart the program I instead get an error telling me `emulator is not a function` instead. If anyone knows what's going on or has a lead please let me know how to resolve the issue!

**Comment by navaneethkm004** [comment]
The main thing is that I haven't updated this bot for a while, so, it's a few discord js and js versions back. thats why its not working. and well sorry i wont be working on this for a few while
